<MyGrid>
	name: name
	email: email1
	latitude: latParam
	GridLayout:
		cols:1
		size: root.width-200, root.height-200
		pos: 100,100

		Label:
			text:'GUI to Db'
			size_hint:0.1,0.1

		GridLayout:
			cols:2
			Label:
				text:"name"
			TextInput:
				id: name
				multiline:False
			Label:
				text:"Email: "
			TextInput:
				id: email1
				multiline:False
			Label:
				text:"latParam: "
			TextInput:
				id: latParam
				multiline:False
		Button:
			text:"Submit"
			on_press:root.btn()
